version: "3.9"
services:
  llm_service:
    build:
      context: .
      dockerfile: Dockerfile.llm
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  audio_service:
    build:
      context: .
      dockerfile: Dockerfile.audio
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  mic_client:
    build:
      context: .
      dockerfile: Dockerfile.mic
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  main_app:
    build:
      context: .
      dockerfile: Dockerfile.main
    depends_on:
      - llm_service
      - audio_service
      - mic_client
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all 